CREATE TABLE element (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, suivi_culture_id INTEGER NOT NULL, zone_id INTEGER DEFAULT NULL, legende_id INTEGER NOT NULL, variete_id INTEGER NOT NULL, date DATETIME NOT NULL, actif BOOLEAN NOT NULL, date_creation DATETIME NOT NULL, date_derniere_maj DATETIME DEFAULT NULL);
CREATE INDEX IDX_41405E391B6BC839 ON element (suivi_culture_id);
CREATE INDEX IDX_41405E399F2C3FAB ON element (zone_id);
CREATE INDEX IDX_41405E39F6B12637 ON element (legende_id);
CREATE INDEX IDX_41405E39620D5460 ON element (variete_id);
CREATE TABLE legende (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, libelle VARCHAR(255) NOT NULL, icone CLOB NOT NULL, actif BOOLEAN NOT NULL, date_creation DATETIME NOT NULL, date_derniere_maj DATETIME DEFAULT NULL);
CREATE TABLE suivi_culture (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, echec BOOLEAN NOT NULL, commentaire CLOB DEFAULT NULL, actif BOOLEAN NOT NULL, date_creation DATETIME NOT NULL, date_derniere_maj DATETIME DEFAULT NULL);
CREATE TABLE variete (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, libelle VARCHAR(255) NOT NULL, actif BOOLEAN NOT NULL, date_creation DATETIME NOT NULL, date_derniere_maj DATETIME DEFAULT NULL);
CREATE TABLE zone (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, libelle VARCHAR(255) NOT NULL, image CLOB NOT NULL, actif BOOLEAN NOT NULL, date_creation DATETIME NOT NULL, date_derniere_maj DATETIME DEFAULT NULL);
DROP TABLE migration_versions;
DROP INDEX IDX_1FF7F711670C757F;
DROP INDEX IDX_1FF7F711B108249D;
CREATE TEMPORARY TABLE __temp__achat_nourriture AS SELECT id, culture_id, fournisseur_id, actif, date, date_creation, date_derniere_maj, poids, prix_paye FROM achat_nourriture;
DROP TABLE achat_nourriture;
CREATE TABLE achat_nourriture (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, culture_id INTEGER NOT NULL, fournisseur_id INTEGER DEFAULT NULL, actif BOOLEAN NOT NULL, date DATETIME DEFAULT NULL, date_creation DATETIME NOT NULL, date_derniere_maj DATETIME DEFAULT NULL, poids DOUBLE PRECISION NOT NULL, prix_paye DOUBLE PRECISION NOT NULL, CONSTRAINT FK_1FF7F711B108249D FOREIGN KEY (culture_id) REFERENCES culture (id) NOT DEFERRABLE INITIALLY IMMEDIATE, CONSTRAINT FK_1FF7F711670C757F FOREIGN KEY (fournisseur_id) REFERENCES fournisseur (id) NOT DEFERRABLE INITIALLY IMMEDIATE);
INSERT INTO achat_nourriture (id, culture_id, fournisseur_id, actif, date, date_creation, date_derniere_maj, poids, prix_paye) SELECT id, culture_id, fournisseur_id, actif, date, date_creation, date_derniere_maj, poids, prix_paye FROM __temp__achat_nourriture;
DROP TABLE __temp__achat_nourriture;
CREATE INDEX IDX_1FF7F711670C757F ON achat_nourriture (fournisseur_id);
CREATE INDEX IDX_1FF7F711B108249D ON achat_nourriture (culture_id);
DROP INDEX IDX_3433713CB108249D;
CREATE TEMPORARY TABLE __temp__recolte AS SELECT id, culture_id, actif, date_creation, date_derniere_maj, commentaire, date, poids FROM recolte;
DROP TABLE recolte;
CREATE TABLE recolte (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, culture_id INTEGER NOT NULL, actif BOOLEAN NOT NULL, date_creation DATETIME NOT NULL, date_derniere_maj DATETIME DEFAULT NULL, commentaire VARCHAR(255) DEFAULT NULL COLLATE BINARY, date DATETIME DEFAULT NULL, poids DOUBLE PRECISION NOT NULL, CONSTRAINT FK_3433713CB108249D FOREIGN KEY (culture_id) REFERENCES culture (id) NOT DEFERRABLE INITIALLY IMMEDIATE);
INSERT INTO recolte (id, culture_id, actif, date_creation, date_derniere_maj, commentaire, date, poids) SELECT id, culture_id, actif, date_creation, date_derniere_maj, commentaire, date, poids FROM __temp__recolte;
DROP TABLE __temp__recolte;
CREATE INDEX IDX_3433713CB108249D ON recolte (culture_id);
DROP INDEX IDX_93872075C54C8C93;
CREATE TEMPORARY TABLE __temp__tache AS SELECT id, type_id, actif, date, date_creation, date_derniere_maj, heure_debut, heure_fin, libelle FROM tache;
DROP TABLE tache;
CREATE TABLE tache (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, type_id INTEGER DEFAULT NULL, actif BOOLEAN NOT NULL, date DATETIME NOT NULL, date_creation DATETIME NOT NULL, date_derniere_maj DATETIME DEFAULT NULL, heure_debut TIME NOT NULL, heure_fin TIME DEFAULT NULL, libelle VARCHAR(255) NOT NULL COLLATE BINARY, CONSTRAINT FK_93872075C54C8C93 FOREIGN KEY (type_id) REFERENCES tache_type (id) NOT DEFERRABLE INITIALLY IMMEDIATE);
INSERT INTO tache (id, type_id, actif, date, date_creation, date_derniere_maj, heure_debut, heure_fin, libelle) SELECT id, type_id, actif, date, date_creation, date_derniere_maj, heure_debut, heure_fin, libelle FROM __temp__tache;
DROP TABLE __temp__tache;
CREATE INDEX IDX_93872075C54C8C93 ON tache (type_id);
DROP INDEX IDX_3B44428D2235D39;
DROP INDEX IDX_3B444289B0F88B1;
CREATE TEMPORARY TABLE __temp__tache_activite AS SELECT tache_id, activite_id FROM tache_activite;
DROP TABLE tache_activite;
CREATE TABLE tache_activite (tache_id INTEGER NOT NULL, activite_id INTEGER NOT NULL, PRIMARY KEY(tache_id, activite_id), CONSTRAINT FK_3B44428D2235D39 FOREIGN KEY (tache_id) REFERENCES tache (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE, CONSTRAINT FK_3B444289B0F88B1 FOREIGN KEY (activite_id) REFERENCES activite (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE);
INSERT INTO tache_activite (tache_id, activite_id) SELECT tache_id, activite_id FROM __temp__tache_activite;
DROP TABLE __temp__tache_activite;
CREATE INDEX IDX_3B44428D2235D39 ON tache_activite (tache_id);
CREATE INDEX IDX_3B444289B0F88B1 ON tache_activite (activite_id);
DROP INDEX IDX_BCE9A358D2235D39;
DROP INDEX IDX_BCE9A358C18272;
CREATE TEMPORARY TABLE __temp__tache_projet AS SELECT tache_id, projet_id FROM tache_projet;
DROP TABLE tache_projet;
CREATE TABLE tache_projet (tache_id INTEGER NOT NULL, projet_id INTEGER NOT NULL, PRIMARY KEY(tache_id, projet_id), CONSTRAINT FK_BCE9A358D2235D39 FOREIGN KEY (tache_id) REFERENCES tache (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE, CONSTRAINT FK_BCE9A358C18272 FOREIGN KEY (projet_id) REFERENCES projet (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE);
INSERT INTO tache_projet (tache_id, projet_id) SELECT tache_id, projet_id FROM __temp__tache_projet;
DROP TABLE __temp__tache_projet;
CREATE INDEX IDX_BCE9A358D2235D39 ON tache_projet (tache_id);
CREATE INDEX IDX_BCE9A358C18272 ON tache_projet (projet_id);